name: CI

on:
  schedule:
    - cron: "30 1 * * */2"
  workflow_dispatch:

jobs:
  update:
    name: Upgrade hook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install pre-commit-mirror-maker
      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: |
          pre-commit-mirror . \
            --language=node \
            --id=pyright \
            --package-name=pyright \
            --entry="pyright" \
            --types=python
      - run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git push origin HEAD:refs/heads/main --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
